services:
  postgres:
    image: postgres:16
    container_name: local-web-api-psql
    environment:
      POSTGRES_DB: database
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d database"]
      interval: 5s
      timeout: 5s
      retries: 5
volumes:
  postgres_data: